name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.4
  dio: ^5.8.0+1
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  flutter_masked_text2: ^0.9.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.0.0
  kakao_flutter_sdk: ^1.9.7+3
  fluttertoast: ^8.2.12
  carousel_slider: ^5.0.0
  web_socket_channel: ^3.0.2
  uuid: ^4.5.1
  stomp_dart_client: ^2.1.3
  flutter_naver_login: ^2.0.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat-SemiBold.ttf


